/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReconcileRouteImport } from './routes/_authenticated/reconcile'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedBedsRouteImport } from './routes/_authenticated/beds'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as ApiPublicHooksBridgeSyncRouteImport } from './routes/api/public/hooks/bridge-sync'
import { Route as ApiPublicHealthSchemaRouteImport } from './routes/api/public/health.schema'
import { Route as ApiPublicBridgeVerifySignatureRouteImport } from './routes/api/public/bridge.verify-signature'
import { Route as ApiPublicBridgeReferralsRouteImport } from './routes/api/public/bridge.referrals'
import { Route as ApiPublicBridgePatientsRouteImport } from './routes/api/public/bridge.patients'
import { Route as ApiPublicBridgeOpenapiRouteImport } from './routes/api/public/bridge.openapi'
import { Route as ApiPublicBridgeNotificationsRouteImport } from './routes/api/public/bridge.notifications'
import { Route as ApiPublicBridgeMicrobiologyRouteImport } from './routes/api/public/bridge.microbiology'
import { Route as ApiPublicBridgeInvestigationsRouteImport } from './routes/api/public/bridge.investigations'
import { Route as ApiPublicBridgeHealthRouteImport } from './routes/api/public/bridge.health'
import { Route as ApiPublicBridgeBedsRouteImport } from './routes/api/public/bridge.beds'
import { Route as ApiPublicBridgeAuditRouteImport } from './routes/api/public/bridge.audit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReconcileRoute = AuthenticatedReconcileRouteImport.update({
  id: '/reconcile',
  path: '/reconcile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBedsRoute = AuthenticatedBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedPatientsRoute,
  } as any)
const ApiPublicHooksBridgeSyncRoute =
  ApiPublicHooksBridgeSyncRouteImport.update({
    id: '/api/public/hooks/bridge-sync',
    path: '/api/public/hooks/bridge-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHealthSchemaRoute = ApiPublicHealthSchemaRouteImport.update({
  id: '/api/public/health/schema',
  path: '/api/public/health/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeVerifySignatureRoute =
  ApiPublicBridgeVerifySignatureRouteImport.update({
    id: '/api/public/bridge/verify-signature',
    path: '/api/public/bridge/verify-signature',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeReferralsRoute =
  ApiPublicBridgeReferralsRouteImport.update({
    id: '/api/public/bridge/referrals',
    path: '/api/public/bridge/referrals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgePatientsRoute = ApiPublicBridgePatientsRouteImport.update({
  id: '/api/public/bridge/patients',
  path: '/api/public/bridge/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeOpenapiRoute = ApiPublicBridgeOpenapiRouteImport.update({
  id: '/api/public/bridge/openapi',
  path: '/api/public/bridge/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeNotificationsRoute =
  ApiPublicBridgeNotificationsRouteImport.update({
    id: '/api/public/bridge/notifications',
    path: '/api/public/bridge/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeMicrobiologyRoute =
  ApiPublicBridgeMicrobiologyRouteImport.update({
    id: '/api/public/bridge/microbiology',
    path: '/api/public/bridge/microbiology',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeInvestigationsRoute =
  ApiPublicBridgeInvestigationsRouteImport.update({
    id: '/api/public/bridge/investigations',
    path: '/api/public/bridge/investigations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeHealthRoute = ApiPublicBridgeHealthRouteImport.update({
  id: '/api/public/bridge/health',
  path: '/api/public/bridge/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeBedsRoute = ApiPublicBridgeBedsRouteImport.update({
  id: '/api/public/bridge/beds',
  path: '/api/public/bridge/beds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeAuditRoute = ApiPublicBridgeAuditRouteImport.update({
  id: '/api/public/bridge/audit',
  path: '/api/public/bridge/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/beds': typeof AuthenticatedBedsRoute
  '/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/reconcile': typeof AuthenticatedReconcileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/api/public/bridge/audit': typeof ApiPublicBridgeAuditRoute
  '/api/public/bridge/beds': typeof ApiPublicBridgeBedsRoute
  '/api/public/bridge/health': typeof ApiPublicBridgeHealthRoute
  '/api/public/bridge/investigations': typeof ApiPublicBridgeInvestigationsRoute
  '/api/public/bridge/microbiology': typeof ApiPublicBridgeMicrobiologyRoute
  '/api/public/bridge/notifications': typeof ApiPublicBridgeNotificationsRoute
  '/api/public/bridge/openapi': typeof ApiPublicBridgeOpenapiRoute
  '/api/public/bridge/patients': typeof ApiPublicBridgePatientsRoute
  '/api/public/bridge/referrals': typeof ApiPublicBridgeReferralsRoute
  '/api/public/bridge/verify-signature': typeof ApiPublicBridgeVerifySignatureRoute
  '/api/public/health/schema': typeof ApiPublicHealthSchemaRoute
  '/api/public/hooks/bridge-sync': typeof ApiPublicHooksBridgeSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/beds': typeof AuthenticatedBedsRoute
  '/reconcile': typeof AuthenticatedReconcileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/api/public/bridge/audit': typeof ApiPublicBridgeAuditRoute
  '/api/public/bridge/beds': typeof ApiPublicBridgeBedsRoute
  '/api/public/bridge/health': typeof ApiPublicBridgeHealthRoute
  '/api/public/bridge/investigations': typeof ApiPublicBridgeInvestigationsRoute
  '/api/public/bridge/microbiology': typeof ApiPublicBridgeMicrobiologyRoute
  '/api/public/bridge/notifications': typeof ApiPublicBridgeNotificationsRoute
  '/api/public/bridge/openapi': typeof ApiPublicBridgeOpenapiRoute
  '/api/public/bridge/patients': typeof ApiPublicBridgePatientsRoute
  '/api/public/bridge/referrals': typeof ApiPublicBridgeReferralsRoute
  '/api/public/bridge/verify-signature': typeof ApiPublicBridgeVerifySignatureRoute
  '/api/public/health/schema': typeof ApiPublicHealthSchemaRoute
  '/api/public/hooks/bridge-sync': typeof ApiPublicHooksBridgeSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/setup': typeof SetupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/beds': typeof AuthenticatedBedsRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRouteWithChildren
  '/_authenticated/reconcile': typeof AuthenticatedReconcileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/api/public/bridge/audit': typeof ApiPublicBridgeAuditRoute
  '/api/public/bridge/beds': typeof ApiPublicBridgeBedsRoute
  '/api/public/bridge/health': typeof ApiPublicBridgeHealthRoute
  '/api/public/bridge/investigations': typeof ApiPublicBridgeInvestigationsRoute
  '/api/public/bridge/microbiology': typeof ApiPublicBridgeMicrobiologyRoute
  '/api/public/bridge/notifications': typeof ApiPublicBridgeNotificationsRoute
  '/api/public/bridge/openapi': typeof ApiPublicBridgeOpenapiRoute
  '/api/public/bridge/patients': typeof ApiPublicBridgePatientsRoute
  '/api/public/bridge/referrals': typeof ApiPublicBridgeReferralsRoute
  '/api/public/bridge/verify-signature': typeof ApiPublicBridgeVerifySignatureRoute
  '/api/public/health/schema': typeof ApiPublicHealthSchemaRoute
  '/api/public/hooks/bridge-sync': typeof ApiPublicHooksBridgeSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/setup'
    | '/admin'
    | '/beds'
    | '/patients'
    | '/reconcile'
    | '/settings'
    | '/patients/$patientId'
    | '/patients/'
    | '/api/public/bridge/audit'
    | '/api/public/bridge/beds'
    | '/api/public/bridge/health'
    | '/api/public/bridge/investigations'
    | '/api/public/bridge/microbiology'
    | '/api/public/bridge/notifications'
    | '/api/public/bridge/openapi'
    | '/api/public/bridge/patients'
    | '/api/public/bridge/referrals'
    | '/api/public/bridge/verify-signature'
    | '/api/public/health/schema'
    | '/api/public/hooks/bridge-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/setup'
    | '/admin'
    | '/beds'
    | '/reconcile'
    | '/settings'
    | '/patients/$patientId'
    | '/patients'
    | '/api/public/bridge/audit'
    | '/api/public/bridge/beds'
    | '/api/public/bridge/health'
    | '/api/public/bridge/investigations'
    | '/api/public/bridge/microbiology'
    | '/api/public/bridge/notifications'
    | '/api/public/bridge/openapi'
    | '/api/public/bridge/patients'
    | '/api/public/bridge/referrals'
    | '/api/public/bridge/verify-signature'
    | '/api/public/health/schema'
    | '/api/public/hooks/bridge-sync'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/setup'
    | '/_authenticated/admin'
    | '/_authenticated/beds'
    | '/_authenticated/patients'
    | '/_authenticated/reconcile'
    | '/_authenticated/settings'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/patients/'
    | '/api/public/bridge/audit'
    | '/api/public/bridge/beds'
    | '/api/public/bridge/health'
    | '/api/public/bridge/investigations'
    | '/api/public/bridge/microbiology'
    | '/api/public/bridge/notifications'
    | '/api/public/bridge/openapi'
    | '/api/public/bridge/patients'
    | '/api/public/bridge/referrals'
    | '/api/public/bridge/verify-signature'
    | '/api/public/health/schema'
    | '/api/public/hooks/bridge-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetupRoute: typeof SetupRoute
  ApiPublicBridgeAuditRoute: typeof ApiPublicBridgeAuditRoute
  ApiPublicBridgeBedsRoute: typeof ApiPublicBridgeBedsRoute
  ApiPublicBridgeHealthRoute: typeof ApiPublicBridgeHealthRoute
  ApiPublicBridgeInvestigationsRoute: typeof ApiPublicBridgeInvestigationsRoute
  ApiPublicBridgeMicrobiologyRoute: typeof ApiPublicBridgeMicrobiologyRoute
  ApiPublicBridgeNotificationsRoute: typeof ApiPublicBridgeNotificationsRoute
  ApiPublicBridgeOpenapiRoute: typeof ApiPublicBridgeOpenapiRoute
  ApiPublicBridgePatientsRoute: typeof ApiPublicBridgePatientsRoute
  ApiPublicBridgeReferralsRoute: typeof ApiPublicBridgeReferralsRoute
  ApiPublicBridgeVerifySignatureRoute: typeof ApiPublicBridgeVerifySignatureRoute
  ApiPublicHealthSchemaRoute: typeof ApiPublicHealthSchemaRoute
  ApiPublicHooksBridgeSyncRoute: typeof ApiPublicHooksBridgeSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconcile': {
      id: '/_authenticated/reconcile'
      path: '/reconcile'
      fullPath: '/reconcile'
      preLoaderRoute: typeof AuthenticatedReconcileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beds': {
      id: '/_authenticated/beds'
      path: '/beds'
      fullPath: '/beds'
      preLoaderRoute: typeof AuthenticatedBedsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedPatientsRoute
    }
    '/api/public/hooks/bridge-sync': {
      id: '/api/public/hooks/bridge-sync'
      path: '/api/public/hooks/bridge-sync'
      fullPath: '/api/public/hooks/bridge-sync'
      preLoaderRoute: typeof ApiPublicHooksBridgeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health/schema': {
      id: '/api/public/health/schema'
      path: '/api/public/health/schema'
      fullPath: '/api/public/health/schema'
      preLoaderRoute: typeof ApiPublicHealthSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/verify-signature': {
      id: '/api/public/bridge/verify-signature'
      path: '/api/public/bridge/verify-signature'
      fullPath: '/api/public/bridge/verify-signature'
      preLoaderRoute: typeof ApiPublicBridgeVerifySignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/referrals': {
      id: '/api/public/bridge/referrals'
      path: '/api/public/bridge/referrals'
      fullPath: '/api/public/bridge/referrals'
      preLoaderRoute: typeof ApiPublicBridgeReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/patients': {
      id: '/api/public/bridge/patients'
      path: '/api/public/bridge/patients'
      fullPath: '/api/public/bridge/patients'
      preLoaderRoute: typeof ApiPublicBridgePatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/openapi': {
      id: '/api/public/bridge/openapi'
      path: '/api/public/bridge/openapi'
      fullPath: '/api/public/bridge/openapi'
      preLoaderRoute: typeof ApiPublicBridgeOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/notifications': {
      id: '/api/public/bridge/notifications'
      path: '/api/public/bridge/notifications'
      fullPath: '/api/public/bridge/notifications'
      preLoaderRoute: typeof ApiPublicBridgeNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/microbiology': {
      id: '/api/public/bridge/microbiology'
      path: '/api/public/bridge/microbiology'
      fullPath: '/api/public/bridge/microbiology'
      preLoaderRoute: typeof ApiPublicBridgeMicrobiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/investigations': {
      id: '/api/public/bridge/investigations'
      path: '/api/public/bridge/investigations'
      fullPath: '/api/public/bridge/investigations'
      preLoaderRoute: typeof ApiPublicBridgeInvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/health': {
      id: '/api/public/bridge/health'
      path: '/api/public/bridge/health'
      fullPath: '/api/public/bridge/health'
      preLoaderRoute: typeof ApiPublicBridgeHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/beds': {
      id: '/api/public/bridge/beds'
      path: '/api/public/bridge/beds'
      fullPath: '/api/public/bridge/beds'
      preLoaderRoute: typeof ApiPublicBridgeBedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/audit': {
      id: '/api/public/bridge/audit'
      path: '/api/public/bridge/audit'
      fullPath: '/api/public/bridge/audit'
      preLoaderRoute: typeof ApiPublicBridgeAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedPatientsRouteChildren {
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedPatientsRouteChildren: AuthenticatedPatientsRouteChildren = {
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedPatientsRouteWithChildren =
  AuthenticatedPatientsRoute._addFileChildren(
    AuthenticatedPatientsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBedsRoute: typeof AuthenticatedBedsRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRouteWithChildren
  AuthenticatedReconcileRoute: typeof AuthenticatedReconcileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBedsRoute: AuthenticatedBedsRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRouteWithChildren,
  AuthenticatedReconcileRoute: AuthenticatedReconcileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetupRoute: SetupRoute,
  ApiPublicBridgeAuditRoute: ApiPublicBridgeAuditRoute,
  ApiPublicBridgeBedsRoute: ApiPublicBridgeBedsRoute,
  ApiPublicBridgeHealthRoute: ApiPublicBridgeHealthRoute,
  ApiPublicBridgeInvestigationsRoute: ApiPublicBridgeInvestigationsRoute,
  ApiPublicBridgeMicrobiologyRoute: ApiPublicBridgeMicrobiologyRoute,
  ApiPublicBridgeNotificationsRoute: ApiPublicBridgeNotificationsRoute,
  ApiPublicBridgeOpenapiRoute: ApiPublicBridgeOpenapiRoute,
  ApiPublicBridgePatientsRoute: ApiPublicBridgePatientsRoute,
  ApiPublicBridgeReferralsRoute: ApiPublicBridgeReferralsRoute,
  ApiPublicBridgeVerifySignatureRoute: ApiPublicBridgeVerifySignatureRoute,
  ApiPublicHealthSchemaRoute: ApiPublicHealthSchemaRoute,
  ApiPublicHooksBridgeSyncRoute: ApiPublicHooksBridgeSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
